username = "fixtureTest"
password = "test"
character_name = "fixture123"
gender = 0
login_addr = "127.0.0.1:8484"
world_addr = "127.0.0.1:8485"

[[players]]
role = "sender"
username = "whispra"
password = "test"
character_name = "whispraChar"
gender = 0

[[players]]
role = "recipient"
username = "whisprb"
password = "test"
character_name = "whisprbChar"
gender = 0
